### ISSUE TITLE
Thanks, and....

### ISSUE THREAD

**Issue by mrwiwi** [gtxaspec/shadowroot#5]
Thanks 1st, I finally have good experience on Linux (manjaro) et even tried on CHROME OS with brunch, so far so good !

Do you think you could adapt the process to use shadow under Wayland Linux ? (if I understand correctly chromeos is using Wayland already, and you made what is presented as impossible until now !)

Thanks again and again, no more reason to keep Windows on daily basis !

**Comment by gtxaspec** [comment]
No, we can not, since the Shadow client itself does not work with wayland (yet)

Shadow will officially support wayland in the future, but not yet, maybe soon.
